#!/bin/bash
# [How to] Install mysql 5.7

#Copy the key from https://dev.mysql.com/doc/refman/5.7/en/checking-gpg-signature.html
sudo apt-key add signature.key

# add apt repo
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'

# update apt
sudo apt update

# check your available versions
sudo apt-cache policy mysql-server

# install mysql [5.7 in this case]
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
